/*
 * Gatekeeper
 *
 * Handles OIDC authentication for static web apps
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	_ "embed"
	"fmt"
	"log"

	"github.com/deifyed/gatekeeper/pkg/config"

	sw "github.com/deifyed/gatekeeper/pkg/core"
)

//go:embed specification.yaml
var specification []byte //nolint:gochecknoglobals

func main() {
	log.Printf("Server started")

	cfg := config.LoadConfig()

	err := cfg.Validate()
	if err != nil {
		log.Fatal(err)
	}

	router := sw.NewRouter(cfg, specification)

	log.Fatal(router.Run(fmt.Sprintf(":%s", cfg.Port)))
}
