version: '3.9'

services:
  auth:
    image: jboss/keycloak:12.0.4
    ports:
    - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /data/gatekeeper-realm.json
      DB_VENDOR: h2
    volumes:
      - type: bind
        source: ./data/keycloak
        target: /data
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8080/auth']
      interval: 4s

  upstream:
    build: ./gin-upstream
    environment:
      DISCOVERY_URL: http://auth:8080/auth/realms/gtkp/.well-known/openid-configuration
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:3000/open']
      interval: 4s
    depends_on:
      auth:
        condition: service_healthy

  frontend:
    build: ./vue-frontend/
    ports:
    - 8000:80
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost']
      interval: 4s
