/*
 * Gatekeeper
 *
 * Handles OIDC authentication for static web apps
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Proxy -
func Proxy(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
