/*
 * Reference Upstream
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/deifyed/gin-upstream/pkg/core"
)

func main() {
	log.Printf("Server started")

	router := core.NewRouter()

	log.Fatal(router.Run(":3000"))
}
